// Regenerate src/auth/assets/inlander-font.ts from the client's webfont.
//
// The sign-in page inlines Inlander as a data URI rather than linking it from
// play.realmvtt.com: a cross-origin webfont needs CORS headers AND a CSP font-src
// exception, and if either is missing the logo silently falls back to serif and
// stops looking like the app.
//
// Usage: node scripts/embed-font.mjs [path-to-woff2]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source =
  process.argv[2] ||
  join(root, "..", "realm15-client", "public", "assets", "fonts", "inlander_regular-webfont.woff2");

const font = readFileSync(source);
const base64 = font.toString("base64");

writeFileSync(
  join(root, "src", "auth", "assets", "inlander-font.ts"),
  `// Generated by scripts/embed-font.mjs — do not edit by hand.
// The Inlander webfont (the Realm VTT logo face), inlined so the sign-in page renders
// identically with no network fetch, no CORS negotiation and no CSP font-src exception.
export const INLANDER_WOFF2_BASE64 =
  "${base64}";
`,
);

console.log(`embedded ${source} (${font.length} bytes → ${base64.length} base64 chars)`);
